class InternalError(Exception):
    pass


class RecognitionError(Exception):
    pass
